### ISSUE TITLE
not working on apple silicon mac

### ISSUE THREAD

**Issue by kbidlack** [dxbednarczyk/mxw#2]
Not sure if I'm doing something wrong here, but I recently got an apple silicon mac (m2) and when I've used this tool (and the original mow) it doesn't detect my mouse (`error: no matching device found`). All I've done is cloned the repository, run `cargo build --release`, and move the binary to `/usr/local/bin`. 
I have an old Python script I was messing around with, and that identifies the device correctly and is able to read the battery from it fine, so it seems to be a problem solely with this project... but I'm not sure what.

**Comment by iguanajuice** [comment]
I'm not on a Mac or using an ARM CPU, but I'm getting the same problem.

I've done the exact same steps, including rebooting after plugging in the mouse and running `mxw` as root.

**Comment by kbidlack** [comment]
Weird... because it actually seems to be working for me now and I can't replicate the error

**Comment by dkbednarczyk** [comment]
This was closed by an unrelated PR, but I've got my hands on an M3 Mac now and can confirm that after f62c087, works fine
