### ISSUE TITLE
A license?

### ISSUE THREAD

**Issue by n3oney** [dxbednarczyk/mxw#3]
Hi, thank you for maintaining this fork, I can confirm it works on NixOS on my Model O Wireless.
Just a quick question though, could you add a LICENSE to this repository?

Thanks.

**Comment by dkbednarczyk** [comment]
Sorry for the (very) late response. See [here](https://softwareengineering.stackexchange.com/a/148165).

The owner of the original repository created it as a personal project, which (at least in the US, where I live) constitutes it as their own copyrighted content. Therefore this repository is _technically_ only for personal use.

**Comment by n3oney** [comment]
I asked the author of the original repo, and now it's under MIT! korkje/mow#16

**Comment by dkbednarczyk** [comment]
Added in e7b1174.
